import { db, technicalDeepDives } from '@/lib/db';
import { eq } from 'drizzle-orm';

// Technical terms with quick definitions (used for inline hover cards)
// These are common football terms that appear in articles
export const TECHNICAL_TERMS: Record<string, { definition: string; category: string }> = {
  // Aerodynamics
  'downforce': {
    definition: 'The aerodynamic force pushing the car down onto the track, increasing grip and cornering speed.',
    category: 'aerodynamics',
  },
  'drag': {
    definition: 'Air resistance that slows the car down. Teams balance drag vs downforce for each circuit.',
    category: 'aerodynamics',
  },
  'diffuser': {
    definition: 'The shaped section under the rear of the car that accelerates airflow to create downforce.',
    category: 'aerodynamics',
  },
  'floor': {
    definition: 'The underside of the car, crucial for generating ground effect downforce in modern motorsport.',
    category: 'aerodynamics',
  },
  'ground effect': {
    definition: 'Downforce generated by shaping the underside of the car to accelerate air beneath it.',
    category: 'aerodynamics',
  },
  'porpoising': {
    definition: 'Bouncing caused when ground effect aerodynamics stall and recover rapidly at high speed.',
    category: 'aerodynamics',
  },
  'sidepod': {
    definition: 'The bodywork alongside the cockpit housing radiators and shaping airflow around the car.',
    category: 'aerodynamics',
  },
  'front wing': {
    definition: 'The aerodynamic device at the front that generates downforce and directs airflow.',
    category: 'aerodynamics',
  },
  'rear wing': {
    definition: 'The large wing at the back providing downforce, with adjustable DRS flap for straights.',
    category: 'aerodynamics',
  },
  'drs': {
    definition: 'Drag Reduction System - a movable rear wing flap that reduces drag for overtaking.',
    category: 'aerodynamics',
  },

  // Power Unit
  'mgu-k': {
    definition: 'Motor Generator Unit - Kinetic. Harvests energy from braking and provides extra power.',
    category: 'power_unit',
  },
  'mgu-h': {
    definition: 'Motor Generator Unit - Heat. Harvests energy from exhaust gases and eliminates turbo lag.',
    category: 'power_unit',
  },
  'ers': {
    definition: 'Energy Recovery System - the combined MGU-K and MGU-H hybrid system.',
    category: 'power_unit',
  },
  'power unit': {
    definition: 'The complete engine package: internal combustion engine plus hybrid components.',
    category: 'power_unit',
  },
  'turbo': {
    definition: 'Turbocharger that compresses intake air using exhaust gases for more power.',
    category: 'power_unit',
  },

  // Strategy
  'undercut': {
    definition: 'Pitting before a rival to gain track position through faster laps on fresh tyres.',
    category: 'strategy',
  },
  'overcut': {
    definition: 'Staying out longer than a rival, hoping their new tyres won\'t be fast enough.',
    category: 'strategy',
  },
  'pit window': {
    definition: 'The optimal range of laps for a pit stop based on tyre degradation and strategy.',
    category: 'strategy',
  },
  'safety car': {
    definition: 'Deployed during incidents to bunch up the field and allow marshals to work safely.',
    category: 'strategy',
  },
  'virtual safety car': {
    definition: 'A digital speed limit applied during minor incidents, maintaining gaps between cars.',
    category: 'strategy',
  },

  // Tyres
  'degradation': {
    definition: 'The rate at which tyres lose performance over a stint due to wear and heat.',
    category: 'tyres',
  },
  'graining': {
    definition: 'When tyre rubber balls up on the surface, reducing grip until it clears.',
    category: 'tyres',
  },
  'blistering': {
    definition: 'Overheating causing the tyre surface to bubble, permanently damaging performance.',
    category: 'tyres',
  },
  'compound': {
    definition: 'The rubber mixture of a tyre. Softer compounds grip better but wear faster.',
    category: 'tyres',
  },

  // Regulations
  'cost cap': {
    definition: 'The budget limit teams must operate under, currently around $135 million per season.',
    category: 'regulations',
  },
  'parc fermé': {
    definition: 'Closed park rules that restrict car changes between qualifying and the race.',
    category: 'regulations',
  },
  'technical directive': {
    definition: 'FIA clarifications on regulations, sometimes introducing new interpretations.',
    category: 'regulations',
  },
};

export interface AnnotatedTerm {
  term: string;
  definition: string;
  category: string;
  deepDiveSlug?: string;
}

/**
 * Find technical terms in text and return their positions
 */
export function findTechnicalTerms(text: string): { term: string; start: number; end: number; info: AnnotatedTerm }[] {
  const results: { term: string; start: number; end: number; info: AnnotatedTerm }[] = [];
  const lowerText = text.toLowerCase();

  for (const [term, info] of Object.entries(TECHNICAL_TERMS)) {
    // Use word boundary matching to find whole words only
    const regex = new RegExp(`\\b${escapeRegex(term)}\\b`, 'gi');
    let match;

    while ((match = regex.exec(text)) !== null) {
      // Avoid overlapping matches
      const overlaps = results.some(
        r => (match!.index >= r.start && match!.index < r.end) ||
             (match!.index + term.length > r.start && match!.index + term.length <= r.end)
      );

      if (!overlaps) {
        results.push({
          term: match[0], // Preserve original casing
          start: match.index,
          end: match.index + match[0].length,
          info: {
            term: capitalize(term),
            definition: info.definition,
            category: info.category,
          },
        });
      }
    }
  }

  // Sort by position
  return results.sort((a, b) => a.start - b.start);
}

/**
 * Get terms that have matching deep dives
 */
export async function getDeepDiveMatches(terms: string[]): Promise<Map<string, string>> {
  const matches = new Map<string, string>();

  // Query deep dives that match any of the terms
  const deepDives = await db
    .select({
      title: technicalDeepDives.title,
      slug: technicalDeepDives.slug,
      tags: technicalDeepDives.tags,
    })
    .from(technicalDeepDives)
    .where(eq(technicalDeepDives.isPublished, true));

  for (const term of terms) {
    const lowerTerm = term.toLowerCase();
    for (const dd of deepDives) {
      const titleMatch = dd.title.toLowerCase().includes(lowerTerm);
      const tagMatch = dd.tags?.some(t => t.toLowerCase().includes(lowerTerm));
      if (titleMatch || tagMatch) {
        matches.set(lowerTerm, dd.slug);
        break;
      }
    }
  }

  return matches;
}

function escapeRegex(string: string): string {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function capitalize(str: string): string {
  return str.split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
}
