// 2025/26 Premier League clubs with their colors
export const PL_CLUBS = {
  'arsenal': {
    name: 'Arsenal',
    shortName: 'Arsenal',
    code: 'ARS',
    primaryColor: '#EF0107',
    secondaryColor: '#FFFFFF',
    stadium: 'Emirates Stadium',
    manager: 'Mikel Arteta',
  },
  'aston-villa': {
    name: 'Aston Villa',
    shortName: 'Villa',
    code: 'AVL',
    primaryColor: '#670E36',
    secondaryColor: '#95BFE5',
    stadium: 'Villa Park',
    manager: 'Unai Emery',
  },
  'bournemouth': {
    name: 'AFC Bournemouth',
    shortName: 'Bournemouth',
    code: 'BOU',
    primaryColor: '#DA291C',
    secondaryColor: '#000000',
    stadium: 'Vitality Stadium',
    manager: 'Andoni Iraola',
  },
  'brentford': {
    name: 'Brentford',
    shortName: 'Brentford',
    code: 'BRE',
    primaryColor: '#E30613',
    secondaryColor: '#FBB800',
    stadium: 'Gtech Community Stadium',
    manager: 'Thomas Frank',
  },
  'brighton': {
    name: 'Brighton & Hove Albion',
    shortName: 'Brighton',
    code: 'BHA',
    primaryColor: '#0057B8',
    secondaryColor: '#FFFFFF',
    stadium: 'Amex Stadium',
    manager: 'Fabian Hurzeler',
  },
  'chelsea': {
    name: 'Chelsea',
    shortName: 'Chelsea',
    code: 'CHE',
    primaryColor: '#034694',
    secondaryColor: '#FFFFFF',
    stadium: 'Stamford Bridge',
    manager: 'Enzo Maresca',
  },
  'crystal-palace': {
    name: 'Crystal Palace',
    shortName: 'Palace',
    code: 'CRY',
    primaryColor: '#1B458F',
    secondaryColor: '#C4122E',
    stadium: 'Selhurst Park',
    manager: 'Oliver Glasner',
  },
  'everton': {
    name: 'Everton',
    shortName: 'Everton',
    code: 'EVE',
    primaryColor: '#003399',
    secondaryColor: '#FFFFFF',
    stadium: 'Goodison Park',
    manager: 'Sean Dyche',
  },
  'fulham': {
    name: 'Fulham',
    shortName: 'Fulham',
    code: 'FUL',
    primaryColor: '#FFFFFF',
    secondaryColor: '#000000',
    stadium: 'Craven Cottage',
    manager: 'Marco Silva',
  },
  'ipswich': {
    name: 'Ipswich Town',
    shortName: 'Ipswich',
    code: 'IPS',
    primaryColor: '#0044AA',
    secondaryColor: '#FFFFFF',
    stadium: 'Portman Road',
    manager: 'Kieran McKenna',
  },
  'leicester': {
    name: 'Leicester City',
    shortName: 'Leicester',
    code: 'LEI',
    primaryColor: '#003090',
    secondaryColor: '#FDBE11',
    stadium: 'King Power Stadium',
    manager: 'Steve Cooper',
  },
  'liverpool': {
    name: 'Liverpool',
    shortName: 'Liverpool',
    code: 'LIV',
    primaryColor: '#C8102E',
    secondaryColor: '#FFFFFF',
    stadium: 'Anfield',
    manager: 'Arne Slot',
  },
  'manchester-city': {
    name: 'Manchester City',
    shortName: 'Man City',
    code: 'MCI',
    primaryColor: '#6CABDD',
    secondaryColor: '#FFFFFF',
    stadium: 'Etihad Stadium',
    manager: 'Pep Guardiola',
  },
  'manchester-united': {
    name: 'Manchester United',
    shortName: 'Man Utd',
    code: 'MUN',
    primaryColor: '#DA291C',
    secondaryColor: '#FBE122',
    stadium: 'Old Trafford',
    manager: 'Ruben Amorim',
  },
  'newcastle': {
    name: 'Newcastle United',
    shortName: 'Newcastle',
    code: 'NEW',
    primaryColor: '#241F20',
    secondaryColor: '#FFFFFF',
    stadium: 'St James\' Park',
    manager: 'Eddie Howe',
  },
  'nottingham-forest': {
    name: 'Nottingham Forest',
    shortName: 'Forest',
    code: 'NFO',
    primaryColor: '#DD0000',
    secondaryColor: '#FFFFFF',
    stadium: 'City Ground',
    manager: 'Nuno Espirito Santo',
  },
  'southampton': {
    name: 'Southampton',
    shortName: 'Southampton',
    code: 'SOU',
    primaryColor: '#D71920',
    secondaryColor: '#FFFFFF',
    stadium: 'St Mary\'s Stadium',
    manager: 'Ivan Juric',
  },
  'tottenham': {
    name: 'Tottenham Hotspur',
    shortName: 'Spurs',
    code: 'TOT',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
    stadium: 'Tottenham Hotspur Stadium',
    manager: 'Ange Postecoglou',
  },
  'west-ham': {
    name: 'West Ham United',
    shortName: 'West Ham',
    code: 'WHU',
    primaryColor: '#7A263A',
    secondaryColor: '#1BB1E7',
    stadium: 'London Stadium',
    manager: 'Julen Lopetegui',
  },
  'wolves': {
    name: 'Wolverhampton Wanderers',
    shortName: 'Wolves',
    code: 'WOL',
    primaryColor: '#FDB913',
    secondaryColor: '#231F20',
    stadium: 'Molineux Stadium',
    manager: 'Gary O\'Neil',
  },
} as const;

export type ClubSlug = keyof typeof PL_CLUBS;
