export const COMPETITIONS = [
  // === Top 5 European Leagues ===
  {
    name: 'Premier League',
    slug: 'premier-league',
    shortName: 'PL',
    type: 'league' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 1,
    apiFootballId: 39,
    description: 'England - Top Flight',
  },
  {
    name: 'La Liga',
    slug: 'la-liga',
    shortName: 'La Liga',
    type: 'league' as const,
    country: 'Spain',
    countryCode: 'ES',
    tier: 1,
    apiFootballId: 140,
    description: 'Spain - Top Flight',
  },
  {
    name: 'Serie A',
    slug: 'serie-a',
    shortName: 'Serie A',
    type: 'league' as const,
    country: 'Italy',
    countryCode: 'IT',
    tier: 1,
    apiFootballId: 135,
    description: 'Italy - Top Flight',
  },
  {
    name: 'Bundesliga',
    slug: 'bundesliga',
    shortName: 'BuLi',
    type: 'league' as const,
    country: 'Germany',
    countryCode: 'DE',
    tier: 1,
    apiFootballId: 78,
    description: 'Germany - Top Flight',
  },
  {
    name: 'Ligue 1',
    slug: 'ligue-1',
    shortName: 'L1',
    type: 'league' as const,
    country: 'France',
    countryCode: 'FR',
    tier: 1,
    apiFootballId: 61,
    description: 'France - Top Flight',
  },
  // === Other European Leagues ===
  {
    name: 'Eredivisie',
    slug: 'eredivisie',
    shortName: 'ERE',
    type: 'league' as const,
    country: 'Netherlands',
    countryCode: 'NL',
    tier: 1,
    apiFootballId: 88,
    description: 'Netherlands - Top Flight',
  },
  {
    name: 'Primeira Liga',
    slug: 'primeira-liga',
    shortName: 'Liga PT',
    type: 'league' as const,
    country: 'Portugal',
    countryCode: 'PT',
    tier: 1,
    apiFootballId: 94,
    description: 'Portugal - Top Flight',
  },
  {
    name: 'Scottish Premiership',
    slug: 'scottish-premiership',
    shortName: 'SPFL',
    type: 'league' as const,
    country: 'Scotland',
    countryCode: 'GB',
    tier: 1,
    apiFootballId: 179,
    description: 'Scotland - Top Flight',
  },
  {
    name: 'Championship',
    slug: 'championship',
    shortName: 'EFL C',
    type: 'league' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 2,
    apiFootballId: 40,
    description: 'England - Second Tier',
  },
  {
    name: 'Belgian Pro League',
    slug: 'belgian-pro-league',
    shortName: 'JPL',
    type: 'league' as const,
    country: 'Belgium',
    countryCode: 'BE',
    tier: 1,
    apiFootballId: 144,
    description: 'Belgium - Top Flight',
  },
  {
    name: 'Turkish Süper Lig',
    slug: 'super-lig',
    shortName: 'SüpLig',
    type: 'league' as const,
    country: 'Turkey',
    countryCode: 'TR',
    tier: 1,
    apiFootballId: 203,
    description: 'Turkey - Top Flight',
  },
  {
    name: 'Austrian Bundesliga',
    slug: 'austrian-bundesliga',
    shortName: 'ÖBL',
    type: 'league' as const,
    country: 'Austria',
    countryCode: 'AT',
    tier: 1,
    apiFootballId: 218,
    description: 'Austria - Top Flight',
  },
  {
    name: 'Swiss Super League',
    slug: 'swiss-super-league',
    shortName: 'SSL',
    type: 'league' as const,
    country: 'Switzerland',
    countryCode: 'CH',
    tier: 1,
    apiFootballId: 207,
    description: 'Switzerland - Top Flight',
  },
  {
    name: 'Danish Superliga',
    slug: 'danish-superliga',
    shortName: 'DSL',
    type: 'league' as const,
    country: 'Denmark',
    countryCode: 'DK',
    tier: 1,
    apiFootballId: 119,
    description: 'Denmark - Top Flight',
  },
  {
    name: 'Greek Super League',
    slug: 'greek-super-league',
    shortName: 'GSL',
    type: 'league' as const,
    country: 'Greece',
    countryCode: 'GR',
    tier: 1,
    apiFootballId: 197,
    description: 'Greece - Top Flight',
  },
  {
    name: 'Croatian First League',
    slug: 'croatian-first-league',
    shortName: 'HNL',
    type: 'league' as const,
    country: 'Croatia',
    countryCode: 'HR',
    tier: 1,
    apiFootballId: 210,
    description: 'Croatia - Top Flight',
  },
  {
    name: 'Czech First League',
    slug: 'czech-first-league',
    shortName: 'CFL',
    type: 'league' as const,
    country: 'Czech Republic',
    countryCode: 'CZ',
    tier: 1,
    apiFootballId: 345,
    description: 'Czech Republic - Top Flight',
  },
  {
    name: 'Polish Ekstraklasa',
    slug: 'ekstraklasa',
    shortName: 'Ekstra',
    type: 'league' as const,
    country: 'Poland',
    countryCode: 'PL',
    tier: 1,
    apiFootballId: 106,
    description: 'Poland - Top Flight',
  },
  {
    name: 'Norwegian Eliteserien',
    slug: 'eliteserien',
    shortName: 'ELS',
    type: 'league' as const,
    country: 'Norway',
    countryCode: 'NO',
    tier: 1,
    apiFootballId: 103,
    description: 'Norway - Top Flight',
  },
  {
    name: 'Swedish Allsvenskan',
    slug: 'allsvenskan',
    shortName: 'ALL',
    type: 'league' as const,
    country: 'Sweden',
    countryCode: 'SE',
    tier: 1,
    apiFootballId: 113,
    description: 'Sweden - Top Flight',
  },
  // === Americas ===
  {
    name: 'MLS',
    slug: 'mls',
    shortName: 'MLS',
    type: 'league' as const,
    country: 'USA',
    countryCode: 'US',
    tier: 1,
    apiFootballId: 253,
    description: 'USA - Major League Soccer',
  },
  {
    name: 'Liga MX',
    slug: 'liga-mx',
    shortName: 'Liga MX',
    type: 'league' as const,
    country: 'Mexico',
    countryCode: 'MX',
    tier: 1,
    apiFootballId: 262,
    description: 'Mexico - Top Flight',
  },
  {
    name: 'Brasileirão Série A',
    slug: 'brasileirao',
    shortName: 'BRA A',
    type: 'league' as const,
    country: 'Brazil',
    countryCode: 'BR',
    tier: 1,
    apiFootballId: 71,
    description: 'Brazil - Top Flight',
  },
  {
    name: 'Argentine Primera División',
    slug: 'argentina-primera',
    shortName: 'ARG',
    type: 'league' as const,
    country: 'Argentina',
    countryCode: 'AR',
    tier: 1,
    apiFootballId: 128,
    description: 'Argentina - Top Flight',
  },
  // === Asia & Middle East ===
  {
    name: 'Saudi Pro League',
    slug: 'saudi-pro-league',
    shortName: 'SPL',
    type: 'league' as const,
    country: 'Saudi Arabia',
    countryCode: 'SA',
    tier: 1,
    apiFootballId: 307,
    description: 'Saudi Arabia - Top Flight',
  },
  {
    name: 'J1 League',
    slug: 'j-league',
    shortName: 'J1',
    type: 'league' as const,
    country: 'Japan',
    countryCode: 'JP',
    tier: 1,
    apiFootballId: 98,
    description: 'Japan - Top Flight',
  },
  {
    name: 'K League 1',
    slug: 'k-league',
    shortName: 'K1',
    type: 'league' as const,
    country: 'South Korea',
    countryCode: 'KR',
    tier: 1,
    apiFootballId: 292,
    description: 'South Korea - Top Flight',
  },
  {
    name: 'Indian Super League',
    slug: 'indian-super-league',
    shortName: 'ISL',
    type: 'league' as const,
    country: 'India',
    countryCode: 'IN',
    tier: 1,
    apiFootballId: 323,
    description: 'India - Top Flight',
  },
  {
    name: 'Chinese Super League',
    slug: 'chinese-super-league',
    shortName: 'CSL',
    type: 'league' as const,
    country: 'China',
    countryCode: 'CN',
    tier: 1,
    apiFootballId: 169,
    description: 'China - Top Flight',
  },
  // === Africa & Oceania ===
  {
    name: 'Egyptian Premier League',
    slug: 'egyptian-premier-league',
    shortName: 'EPL EG',
    type: 'league' as const,
    country: 'Egypt',
    countryCode: 'EG',
    tier: 1,
    apiFootballId: 233,
    description: 'Egypt - Top Flight',
  },
  {
    name: 'South African Premier Division',
    slug: 'south-african-premier',
    shortName: 'PSL',
    type: 'league' as const,
    country: 'South Africa',
    countryCode: 'ZA',
    tier: 1,
    apiFootballId: 288,
    description: 'South Africa - Top Flight',
  },
  {
    name: 'A-League',
    slug: 'a-league',
    shortName: 'A-Lg',
    type: 'league' as const,
    country: 'Australia',
    countryCode: 'AU',
    tier: 1,
    apiFootballId: 188,
    description: 'Australia - Top Flight',
  },
  // === European Cups ===
  {
    name: 'Champions League',
    slug: 'champions-league',
    shortName: 'UCL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 1,
    apiFootballId: 2,
    description: 'Europe - Elite Club Competition',
  },
  {
    name: 'Europa League',
    slug: 'europa-league',
    shortName: 'UEL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 2,
    apiFootballId: 3,
    description: 'Europe - Secondary Club Competition',
  },
  {
    name: 'Conference League',
    slug: 'conference-league',
    shortName: 'UECL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 3,
    apiFootballId: 848,
    description: 'Europe - Third-Tier Club Competition',
  },
  {
    name: 'UEFA Super Cup',
    slug: 'uefa-super-cup',
    shortName: 'USC',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 3,
    apiFootballId: 531,
    description: 'Europe - UCL vs UEL Winners',
  },
  // === Domestic Cups ===
  {
    name: 'FA Cup',
    slug: 'fa-cup',
    shortName: 'FA Cup',
    type: 'cup' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 2,
    apiFootballId: 45,
    description: 'England - Knockout Cup',
  },
  {
    name: 'EFL Cup',
    slug: 'efl-cup',
    shortName: 'EFL Cup',
    type: 'cup' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 3,
    apiFootballId: 48,
    description: 'England - League Cup',
  },
  {
    name: 'Copa del Rey',
    slug: 'copa-del-rey',
    shortName: 'CdR',
    type: 'cup' as const,
    country: 'Spain',
    countryCode: 'ES',
    tier: 2,
    apiFootballId: 143,
    description: 'Spain - Knockout Cup',
  },
  {
    name: 'Coppa Italia',
    slug: 'coppa-italia',
    shortName: 'Coppa',
    type: 'cup' as const,
    country: 'Italy',
    countryCode: 'IT',
    tier: 2,
    apiFootballId: 137,
    description: 'Italy - Knockout Cup',
  },
  {
    name: 'DFB-Pokal',
    slug: 'dfb-pokal',
    shortName: 'DFB',
    type: 'cup' as const,
    country: 'Germany',
    countryCode: 'DE',
    tier: 2,
    apiFootballId: 81,
    description: 'Germany - Knockout Cup',
  },
  {
    name: 'Coupe de France',
    slug: 'coupe-de-france',
    shortName: 'CdF',
    type: 'cup' as const,
    country: 'France',
    countryCode: 'FR',
    tier: 2,
    apiFootballId: 66,
    description: 'France - Knockout Cup',
  },
  // === Continental Cups ===
  {
    name: 'Copa Libertadores',
    slug: 'copa-libertadores',
    shortName: 'Lib',
    type: 'cup' as const,
    country: 'South America',
    countryCode: 'SA',
    tier: 1,
    apiFootballId: 13,
    description: 'South America - Elite Club Competition',
  },
  {
    name: 'Copa Sudamericana',
    slug: 'copa-sudamericana',
    shortName: 'Sud',
    type: 'cup' as const,
    country: 'South America',
    countryCode: 'SA',
    tier: 2,
    apiFootballId: 11,
    description: 'South America - Secondary Club Competition',
  },
  {
    name: 'AFC Champions League',
    slug: 'afc-champions-league',
    shortName: 'ACL',
    type: 'cup' as const,
    country: 'Asia',
    countryCode: 'AS',
    tier: 1,
    apiFootballId: 17,
    description: 'Asia - Elite Club Competition',
  },
  {
    name: 'CAF Champions League',
    slug: 'caf-champions-league',
    shortName: 'CAFCL',
    type: 'cup' as const,
    country: 'Africa',
    countryCode: 'AF',
    tier: 1,
    apiFootballId: 12,
    description: 'Africa - Elite Club Competition',
  },
  {
    name: 'Club World Cup',
    slug: 'club-world-cup',
    shortName: 'CWC',
    type: 'cup' as const,
    country: 'World',
    countryCode: 'WW',
    tier: 1,
    apiFootballId: 15,
    description: 'World - FIFA Club World Cup',
  },
  // === International ===
  {
    name: 'World Cup',
    slug: 'world-cup',
    shortName: 'WC',
    type: 'international' as const,
    country: 'World',
    countryCode: 'WW',
    tier: 1,
    apiFootballId: 1,
    description: 'World - Senior National Teams',
  },
  {
    name: 'European Championship',
    slug: 'euros',
    shortName: 'EUROS',
    type: 'international' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 1,
    apiFootballId: 4,
    description: 'Europe - Senior National Teams',
  },
  {
    name: 'Nations League',
    slug: 'nations-league',
    shortName: 'UNL',
    type: 'international' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 2,
    apiFootballId: 5,
    description: 'Europe - Nations League',
  },
  {
    name: 'Copa America',
    slug: 'copa-america',
    shortName: 'Copa',
    type: 'international' as const,
    country: 'South America',
    countryCode: 'SA',
    tier: 1,
    apiFootballId: 9,
    description: 'South America - Senior National Teams',
  },
  {
    name: 'Africa Cup of Nations',
    slug: 'afcon',
    shortName: 'AFCON',
    type: 'international' as const,
    country: 'Africa',
    countryCode: 'AF',
    tier: 1,
    apiFootballId: 6,
    description: 'Africa - Senior National Teams',
  },
  {
    name: 'Asian Cup',
    slug: 'asian-cup',
    shortName: 'AFC',
    type: 'international' as const,
    country: 'Asia',
    countryCode: 'AS',
    tier: 1,
    apiFootballId: 7,
    description: 'Asia - Senior National Teams',
  },
] as const;

export type CompetitionConfig = (typeof COMPETITIONS)[number];
