export const COMPETITIONS = [
  {
    name: 'Premier League',
    slug: 'premier-league',
    shortName: 'PL',
    type: 'league' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 1,
    apiFootballId: 39,
  },
  {
    name: 'La Liga',
    slug: 'la-liga',
    shortName: 'La Liga',
    type: 'league' as const,
    country: 'Spain',
    countryCode: 'ES',
    tier: 1,
    apiFootballId: 140,
  },
  {
    name: 'Serie A',
    slug: 'serie-a',
    shortName: 'Serie A',
    type: 'league' as const,
    country: 'Italy',
    countryCode: 'IT',
    tier: 1,
    apiFootballId: 135,
  },
  {
    name: 'Bundesliga',
    slug: 'bundesliga',
    shortName: 'BuLi',
    type: 'league' as const,
    country: 'Germany',
    countryCode: 'DE',
    tier: 1,
    apiFootballId: 78,
  },
  {
    name: 'Ligue 1',
    slug: 'ligue-1',
    shortName: 'L1',
    type: 'league' as const,
    country: 'France',
    countryCode: 'FR',
    tier: 1,
    apiFootballId: 61,
  },
  {
    name: 'Champions League',
    slug: 'champions-league',
    shortName: 'UCL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 1,
    apiFootballId: 2,
  },
  {
    name: 'Europa League',
    slug: 'europa-league',
    shortName: 'UEL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 2,
    apiFootballId: 3,
  },
  {
    name: 'FA Cup',
    slug: 'fa-cup',
    shortName: 'FA Cup',
    type: 'cup' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 2,
    apiFootballId: 45,
  },
  {
    name: 'EFL Cup',
    slug: 'efl-cup',
    shortName: 'EFL Cup',
    type: 'cup' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 3,
    apiFootballId: 48,
  },
  {
    name: 'World Cup',
    slug: 'world-cup',
    shortName: 'WC',
    type: 'international' as const,
    country: 'World',
    countryCode: 'WW',
    tier: 1,
    apiFootballId: 1,
  },
] as const;

export type CompetitionConfig = (typeof COMPETITIONS)[number];
