export const COMPETITIONS = [
  // === Leagues ===
  {
    name: 'Premier League',
    slug: 'premier-league',
    shortName: 'PL',
    type: 'league' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 1,
    apiFootballId: 39,
    description: 'England - Top Flight',
  },
  {
    name: 'La Liga',
    slug: 'la-liga',
    shortName: 'La Liga',
    type: 'league' as const,
    country: 'Spain',
    countryCode: 'ES',
    tier: 1,
    apiFootballId: 140,
    description: 'Spain - Top Flight',
  },
  {
    name: 'Serie A',
    slug: 'serie-a',
    shortName: 'Serie A',
    type: 'league' as const,
    country: 'Italy',
    countryCode: 'IT',
    tier: 1,
    apiFootballId: 135,
    description: 'Italy - Top Flight',
  },
  {
    name: 'Bundesliga',
    slug: 'bundesliga',
    shortName: 'BuLi',
    type: 'league' as const,
    country: 'Germany',
    countryCode: 'DE',
    tier: 1,
    apiFootballId: 78,
    description: 'Germany - Top Flight',
  },
  {
    name: 'Ligue 1',
    slug: 'ligue-1',
    shortName: 'L1',
    type: 'league' as const,
    country: 'France',
    countryCode: 'FR',
    tier: 1,
    apiFootballId: 61,
    description: 'France - Top Flight',
  },
  {
    name: 'Eredivisie',
    slug: 'eredivisie',
    shortName: 'ERE',
    type: 'league' as const,
    country: 'Netherlands',
    countryCode: 'NL',
    tier: 1,
    apiFootballId: 88,
    description: 'Netherlands - Top Flight',
  },
  {
    name: 'Primeira Liga',
    slug: 'primeira-liga',
    shortName: 'Liga PT',
    type: 'league' as const,
    country: 'Portugal',
    countryCode: 'PT',
    tier: 1,
    apiFootballId: 94,
    description: 'Portugal - Top Flight',
  },
  {
    name: 'Scottish Premiership',
    slug: 'scottish-premiership',
    shortName: 'SPFL',
    type: 'league' as const,
    country: 'Scotland',
    countryCode: 'GB',
    tier: 1,
    apiFootballId: 179,
    description: 'Scotland - Top Flight',
  },
  {
    name: 'Championship',
    slug: 'championship',
    shortName: 'EFL C',
    type: 'league' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 2,
    apiFootballId: 40,
    description: 'England - Second Tier',
  },
  // === Cups ===
  {
    name: 'Champions League',
    slug: 'champions-league',
    shortName: 'UCL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 1,
    apiFootballId: 2,
    description: 'Europe - Elite Club Competition',
  },
  {
    name: 'Europa League',
    slug: 'europa-league',
    shortName: 'UEL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 2,
    apiFootballId: 3,
    description: 'Europe - Secondary Club Competition',
  },
  {
    name: 'Conference League',
    slug: 'conference-league',
    shortName: 'UECL',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 3,
    apiFootballId: 848,
    description: 'Europe - Third-Tier Club Competition',
  },
  {
    name: 'FA Cup',
    slug: 'fa-cup',
    shortName: 'FA Cup',
    type: 'cup' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 2,
    apiFootballId: 45,
    description: 'England - Knockout Cup',
  },
  {
    name: 'EFL Cup',
    slug: 'efl-cup',
    shortName: 'EFL Cup',
    type: 'cup' as const,
    country: 'England',
    countryCode: 'GB',
    tier: 3,
    apiFootballId: 48,
    description: 'England - League Cup',
  },
  {
    name: 'Copa del Rey',
    slug: 'copa-del-rey',
    shortName: 'CdR',
    type: 'cup' as const,
    country: 'Spain',
    countryCode: 'ES',
    tier: 2,
    apiFootballId: 143,
    description: 'Spain - Knockout Cup',
  },
  {
    name: 'Coppa Italia',
    slug: 'coppa-italia',
    shortName: 'Coppa',
    type: 'cup' as const,
    country: 'Italy',
    countryCode: 'IT',
    tier: 2,
    apiFootballId: 137,
    description: 'Italy - Knockout Cup',
  },
  {
    name: 'DFB-Pokal',
    slug: 'dfb-pokal',
    shortName: 'DFB',
    type: 'cup' as const,
    country: 'Germany',
    countryCode: 'DE',
    tier: 2,
    apiFootballId: 81,
    description: 'Germany - Knockout Cup',
  },
  {
    name: 'Coupe de France',
    slug: 'coupe-de-france',
    shortName: 'CdF',
    type: 'cup' as const,
    country: 'France',
    countryCode: 'FR',
    tier: 2,
    apiFootballId: 66,
    description: 'France - Knockout Cup',
  },
  {
    name: 'UEFA Super Cup',
    slug: 'uefa-super-cup',
    shortName: 'USC',
    type: 'cup' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 3,
    apiFootballId: 531,
    description: 'Europe - UCL vs UEL Winners',
  },
  // === International ===
  {
    name: 'World Cup',
    slug: 'world-cup',
    shortName: 'WC',
    type: 'international' as const,
    country: 'World',
    countryCode: 'WW',
    tier: 1,
    apiFootballId: 1,
    description: 'World - Senior National Teams',
  },
  {
    name: 'European Championship',
    slug: 'euros',
    shortName: 'EUROS',
    type: 'international' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 1,
    apiFootballId: 4,
    description: 'Europe - Senior National Teams',
  },
  {
    name: 'Nations League',
    slug: 'nations-league',
    shortName: 'UNL',
    type: 'international' as const,
    country: 'Europe',
    countryCode: 'EU',
    tier: 2,
    apiFootballId: 5,
    description: 'Europe - Nations League',
  },
] as const;

export type CompetitionConfig = (typeof COMPETITIONS)[number];
