export const RSS_FEEDS = [
  // === Tier 1 — Broadsheet / Premium ===
  {
    name: 'BBC Sport Football',
    slug: 'bbc-football',
    feedUrl: 'https://feeds.bbci.co.uk/sport/football/rss.xml',
    websiteUrl: 'https://www.bbc.co.uk/sport/football',
    logoUrl: '/images/sources/bbc.png',
    priority: 1,
  },
  {
    name: 'Sky Sports Football',
    slug: 'sky-sports',
    feedUrl: 'https://www.skysports.com/rss/12040',
    websiteUrl: 'https://www.skysports.com/football',
    logoUrl: '/images/sources/skysports.png',
    priority: 1,
  },
  {
    name: 'The Guardian Football',
    slug: 'guardian-football',
    feedUrl: 'https://www.theguardian.com/football/rss',
    websiteUrl: 'https://www.theguardian.com/football',
    logoUrl: '/images/sources/guardian.png',
    priority: 1,
  },
  {
    name: 'The Telegraph Football',
    slug: 'telegraph-football',
    feedUrl: 'https://www.telegraph.co.uk/football/rss.xml',
    websiteUrl: 'https://www.telegraph.co.uk/football/',
    logoUrl: '/images/sources/telegraph.png',
    priority: 1,
  },
  // === Tier 2 — Major outlets ===
  {
    name: 'ESPN FC',
    slug: 'espn-fc',
    feedUrl: 'https://www.espn.com/espn/rss/soccer/news',
    websiteUrl: 'https://www.espn.com/soccer/',
    logoUrl: '/images/sources/espn.png',
    priority: 2,
  },
  {
    name: 'The Independent Football',
    slug: 'independent-football',
    feedUrl: 'https://www.independent.co.uk/sport/football/rss',
    websiteUrl: 'https://www.independent.co.uk/sport/football',
    logoUrl: '/images/sources/independent.png',
    priority: 2,
  },
  {
    name: 'GiveMeSport Football',
    slug: 'givemesport',
    feedUrl: 'https://www.givemesport.com/feed/',
    websiteUrl: 'https://www.givemesport.com/football/',
    logoUrl: '/images/sources/givemesport.png',
    priority: 2,
  },
  {
    name: 'Football Insider',
    slug: 'football-insider',
    feedUrl: 'https://www.footballinsider247.com/feed/',
    websiteUrl: 'https://www.footballinsider247.com',
    logoUrl: '/images/sources/footballinsider.png',
    priority: 2,
  },
  // === Tier 3 — Specialist / transfers ===
  {
    name: 'CaughtOffside',
    slug: 'caughtoffside',
    feedUrl: 'https://www.caughtoffside.com/feed/',
    websiteUrl: 'https://www.caughtoffside.com',
    logoUrl: '/images/sources/caughtoffside.png',
    priority: 3,
  },
  {
    name: 'Football Italia',
    slug: 'football-italia',
    feedUrl: 'https://www.football-italia.net/feed',
    websiteUrl: 'https://www.football-italia.net',
    logoUrl: '/images/sources/footballitalia.png',
    priority: 3,
  },
  {
    name: 'The Football Faithful',
    slug: 'football-faithful',
    feedUrl: 'https://thefootballfaithful.com/feed/',
    websiteUrl: 'https://thefootballfaithful.com',
    logoUrl: '/images/sources/footballfaithful.png',
    priority: 3,
  },
  {
    name: 'Sportslens',
    slug: 'sportslens',
    feedUrl: 'https://sportslens.com/feed/',
    websiteUrl: 'https://sportslens.com/football/',
    logoUrl: '/images/sources/sportslens.png',
    priority: 3,
  },
  // === Tier 4-5 — Tabloid / aggregators ===
  {
    name: 'Mirror Football',
    slug: 'mirror-football',
    feedUrl: 'https://www.mirror.co.uk/sport/football/rss.xml',
    websiteUrl: 'https://www.mirror.co.uk/sport/football/',
    logoUrl: '/images/sources/mirror.png',
    priority: 5,
  },
  {
    name: '90min',
    slug: '90min',
    feedUrl: 'https://www.90min.com/feed',
    websiteUrl: 'https://www.90min.com',
    logoUrl: '/images/sources/90min.png',
    priority: 5,
  },
  {
    name: 'Daily Mail Football',
    slug: 'daily-mail',
    feedUrl: 'https://www.dailymail.co.uk/sport/football/index.rss',
    websiteUrl: 'https://www.dailymail.co.uk/sport/football/',
    logoUrl: '/images/sources/dailymail.png',
    priority: 6,
  },
] as const;

export type RSSFeedSource = (typeof RSS_FEEDS)[number];
