export const RSS_FEEDS = [
  {
    name: 'BBC Sport Football',
    slug: 'bbc-football',
    feedUrl: 'https://feeds.bbci.co.uk/sport/football/rss.xml',
    websiteUrl: 'https://www.bbc.co.uk/sport/football',
    logoUrl: '/images/sources/bbc.png',
    priority: 1,
  },
  {
    name: 'Sky Sports Football',
    slug: 'sky-sports',
    feedUrl: 'https://www.skysports.com/rss/12040',
    websiteUrl: 'https://www.skysports.com/football',
    logoUrl: '/images/sources/skysports.png',
    priority: 1,
  },
  {
    name: 'The Guardian Football',
    slug: 'guardian-football',
    feedUrl: 'https://www.theguardian.com/football/rss',
    websiteUrl: 'https://www.theguardian.com/football',
    logoUrl: '/images/sources/guardian.png',
    priority: 1,
  },
  {
    name: 'ESPN FC',
    slug: 'espn-fc',
    feedUrl: 'https://www.espn.com/espn/rss/soccer/news',
    websiteUrl: 'https://www.espn.com/soccer/',
    logoUrl: '/images/sources/espn.png',
    priority: 2,
  },
  {
    name: 'FourFourTwo',
    slug: 'fourfourtwo',
    feedUrl: 'https://www.fourfourtwo.com/feed',
    websiteUrl: 'https://www.fourfourtwo.com',
    logoUrl: '/images/sources/fourfourtwo.png',
    priority: 2,
  },
  {
    name: 'Goal.com',
    slug: 'goal',
    feedUrl: 'https://www.goal.com/feeds/en/news',
    websiteUrl: 'https://www.goal.com',
    logoUrl: '/images/sources/goal.png',
    priority: 3,
  },
  {
    name: 'Football365',
    slug: 'football365',
    feedUrl: 'https://www.football365.com/feed',
    websiteUrl: 'https://www.football365.com',
    logoUrl: '/images/sources/football365.png',
    priority: 3,
  },
  {
    name: 'TeamTalk',
    slug: 'teamtalk',
    feedUrl: 'https://www.teamtalk.com/feed',
    websiteUrl: 'https://www.teamtalk.com',
    logoUrl: '/images/sources/teamtalk.png',
    priority: 4,
  },
  {
    name: 'Mirror Football',
    slug: 'mirror-football',
    feedUrl: 'https://www.mirror.co.uk/sport/football/rss.xml',
    websiteUrl: 'https://www.mirror.co.uk/sport/football/',
    logoUrl: '/images/sources/mirror.png',
    priority: 5,
  },
  {
    name: '90min',
    slug: '90min',
    feedUrl: 'https://www.90min.com/feed',
    websiteUrl: 'https://www.90min.com',
    logoUrl: '/images/sources/90min.png',
    priority: 5,
  },
  {
    name: 'Football.London',
    slug: 'football-london',
    feedUrl: 'https://www.football.london/rss.xml',
    websiteUrl: 'https://www.football.london',
    logoUrl: '/images/sources/footballlondon.png',
    priority: 4,
  },
  {
    name: 'Tribal Football',
    slug: 'tribal-football',
    feedUrl: 'https://www.tribalfootball.com/feed',
    websiteUrl: 'https://www.tribalfootball.com',
    logoUrl: '/images/sources/tribalfootball.png',
    priority: 6,
  },
] as const;

export type RSSFeedSource = (typeof RSS_FEEDS)[number];
