import { NextResponse } from 'next/server';
import { getSession, isAdmin } from '@/lib/auth';
import { db, newsArticles } from '@/lib/db';
import { like, or, eq, desc } from 'drizzle-orm';
import { downloadImage } from '@/lib/utils/image-downloader';
import { scrapeArticleImage } from '@/lib/utils/scrape-article-image';
import fs from 'fs/promises';
import path from 'path';

export const dynamic = 'force-dynamic';

// Storage path - Railway volume or local fallback
const STORAGE_PATH = process.env.IMAGE_STORAGE_PATH || 'public/images/articles';

function getStorageDir(): string {
  if (process.env.IMAGE_STORAGE_PATH) {
    return process.env.IMAGE_STORAGE_PATH;
  }
  return path.join(process.cwd(), STORAGE_PATH);
}

async function fileExists(filepath: string): Promise<boolean> {
  try {
    await fs.access(filepath);
    return true;
  } catch {
    return false;
  }
}

/**
 * GET /api/admin/fix-images
 * Check how many images are broken (file doesn't exist)
 */
export async function GET() {
  if (!(await isAdmin(await getSession()))) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const storageDir = getStorageDir();

  // Get articles with local image paths
  const articles = await db
    .select({
      id: newsArticles.id,
      imageUrl: newsArticles.imageUrl,
    })
    .from(newsArticles)
    .where(
      or(
        like(newsArticles.imageUrl, '/api/images/%'),
        like(newsArticles.imageUrl, '/images/articles/%')
      )
    );

  let existing = 0;
  let missing = 0;

  for (const article of articles) {
    if (!article.imageUrl) continue;

    // Extract filename from path
    const filename = article.imageUrl.split('/').pop();
    if (!filename) continue;

    const filepath = path.join(storageDir, filename);
    if (await fileExists(filepath)) {
      existing++;
    } else {
      missing++;
    }
  }

  return NextResponse.json({
    total: articles.length,
    existing,
    missing,
    storageDir,
    message: missing > 0
      ? `${missing} images are missing and need to be re-fetched. POST to this endpoint to fix.`
      : 'All images are present!',
  });
}

/**
 * POST /api/admin/fix-images
 * Clear broken image URLs so they can be regenerated
 */
export async function POST() {
  if (!(await isAdmin(await getSession()))) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const storageDir = getStorageDir();

  // Get articles with local image paths
  const articles = await db
    .select({
      id: newsArticles.id,
      title: newsArticles.title,
      imageUrl: newsArticles.imageUrl,
      originalUrl: newsArticles.originalUrl,
    })
    .from(newsArticles)
    .where(
      or(
        like(newsArticles.imageUrl, '/api/images/%'),
        like(newsArticles.imageUrl, '/images/articles/%')
      )
    )
    .orderBy(desc(newsArticles.publishedAt));

  let fixed = 0;
  let cleared = 0;
  let alreadyOk = 0;

  for (const article of articles) {
    if (!article.imageUrl) continue;

    // Extract filename from path
    const filename = article.imageUrl.split('/').pop();
    if (!filename) continue;

    const filepath = path.join(storageDir, filename);

    // Check if file exists
    if (await fileExists(filepath)) {
      alreadyOk++;
      continue;
    }

    // File is missing - try to re-scrape from original article
    if (article.originalUrl) {
      const scrapedUrl = await scrapeArticleImage(article.originalUrl);
      if (scrapedUrl) {
        const downloadResult = await downloadImage(scrapedUrl);
        if (downloadResult.success && downloadResult.localPath) {
          await db
            .update(newsArticles)
            .set({ imageUrl: downloadResult.localPath })
            .where(eq(newsArticles.id, article.id));
          fixed++;
          console.log(`[FixImages] Re-scraped: ${article.title.slice(0, 40)}...`);
          continue;
        }
      }
    }

    // Couldn't fix - clear the URL so AI can regenerate
    await db
      .update(newsArticles)
      .set({ imageUrl: null })
      .where(eq(newsArticles.id, article.id));
    cleared++;
    console.log(`[FixImages] Cleared broken: ${article.title.slice(0, 40)}...`);

    // Small delay to be polite
    await new Promise(r => setTimeout(r, 500));
  }

  return NextResponse.json({
    success: true,
    total: articles.length,
    alreadyOk,
    fixed,
    cleared,
    message: `${fixed} images re-scraped, ${cleared} broken URLs cleared (will be regenerated by cron job)`,
  });
}
